### ISSUE TITLE
关于训练时间

### ISSUE THREAD

**Issue by loserhou** [nullmax-vision/SimPB#2]
您好！按照您的配置我在8张A800训练时训练时间好像要比您多2h左右，这是正常的吗？目前还没训练完成
<img width="239" alt="97e9bcb7870f6fd73f8bf33455bb784" src="https://github.com/user-attachments/assets/3bb6ce34-55fa-47c6-be84-3dec148b6e6e">

**Comment by InchSoup** [comment]
提供的log是用4090训练的，A800训练时间在20小时左右
